name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:
#
# MacOS
#

  osx:
    runs-on: macOS-latest
    name: '🍎 macOS · mcode'
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '⚙️ Dependencies (brew)'
      run: ./scripts/macosx/install-ada.sh

    - name: Build and test GHDL
      run: |
        PATH=$PWD/gnat/bin:$PATH
        ./scripts/ci-run.sh -c
        mv ghdl-*.tgz ghdl-osx-mcode.tgz
      env:
        TASK: macosx+mcode
        GITHUB_OS: ${{ runner.os }}

    - name: '📤 Upload artifact: package'
      uses: actions/upload-artifact@v2
      with:
        path: ghdl-osx-mcode.tgz

#---

# TODO:
# - Cache
#  - 'gnat' directory in macOS job
#
# - Re-package a MINGW/MSYS2 package to provide a 'standalone' tarball/zipfile.
#  - https://github.com/ghdl/ghdl/issues/318#issuecomment-286246287
#
# - Add GNAT GPL 32-bit build job with mcode backend
